{{- if .Values.configmap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bbgo.fullname" . }}
  labels:
    {{- include "bbgo.labels" . | nindent 4 }}
data:
  # if configmap is given as a string, we read it as a file
  {{- if eq "string" (typeOf .Values.configmap) }}
  bbgo.yaml: |-
    {{- .Files.Get .Values.configmap | nindent 4 }}
  {{- else }}
  bbgo.yaml:
    {{- .Values.configmap | nindent 4 }}
  {{- end }}
{{- end }}
