{{- if .Values.metrics.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "bbgo.fullname" . }}
  labels:
    {{- include "bbgo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bbgo.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: metrics
{{- end }}