// Code generated by "callbackgen -type CCI"; DO NOT EDIT.

package cciema

import ()

func (inc *CCILINE) OnUpdate(cb func(value float64)) {
	inc.UpdateCallbacks = append(inc.UpdateCallbacks, cb)
}

func (inc *CCILINE) EmitUpdate(value float64) {
	for _, cb := range inc.UpdateCallbacks {
		cb(value)
	}
}
