---
backtest:
  sessions:
  - max
  startTime: "2022-01-01"
  endTime: "2022-06-18"
  symbols:
  - USDTTWD
  accounts:
    binance:
      balances:
        TWD: 280_000.0

exchangeStrategies:
- on: max
  schedule:
    interval: 1m
    symbol: USDTTWD
    side: buy
    amount: 500

    aboveMovingAverage:
      type: EWMA
      interval: 1h
      window: 99
      side: sell

    belowMovingAverage:
      type: EWMA
      interval: 1h
      window: 99
      side: buy

