---
sessions:
  binance:
    exchange: binance
    envVarPrefix: binance

  binance_margin_dotusdt:
    exchange: binance
    envVarPrefix: binance
    margin: true
    isolatedMargin: true
    isolatedMarginSymbol: DOTUSDT

  max:
    exchange: max
    envVarPrefix: max

  kucoin:
    exchange: kucoin
    envVarPrefix: kucoin

  okex:
    exchange: okex
    envVarPrefix: okex

sync:
  # userDataStream is used to sync the trading data in real-time
  # it uses the websocket connection to insert the trades
  userDataStream:
    trades: true
    filledOrders: true

  # since is the start date of your trading data
  since: 2019-01-01

  # sessions is the list of session names you want to sync
  # by default, BBGO sync all your available sessions.
  sessions:
  - binance
  - binance_margin_dotusdt
  - max
  - okex
  - kucoin

  # symbols is the list of symbols you want to sync
  # by default, BBGO try to guess your symbols by your existing account balances.
  symbols:
  - BTCUSDT
  - ETHUSDT
  - DOTUSDT
  - binance:BNBUSDT
  - max:USDTTWD

  # marginHistory enables the margin history sync
  marginHistory: true

  # marginAssets lists the assets that are used in the margin.
  # including loan, repay, interest and liquidation
  marginAssets:
  - USDT

  depositHistory: true
  rewardHistory: true
  withdrawHistory: true
