---
notifications:
  slack:
    defaultChannel: "dev-bbgo"
    errorChannel: "bbgo-error"

  # if you want to route channel by symbol
  symbolChannels:
    "^BTC": "btc"
    "^ETH": "eth"

  # if you want to route channel by exchange session
  sessionChannels:
    max: "bbgo-max"
    binance: "bbgo-binance"

  # routing rules
  routing:
    trade: "$symbol"
    order: "$slient"
    submitOrder: "$slient"
    pnL: "bbgo-pnl"

sessions:
  max:
    exchange: max
    envVarPrefix: max

  binance:
    exchange: binance
    envVarPrefix: binance

persistence:
  json:
    directory: var/data
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

crossExchangeStrategies:

- xnav:
    interval: 1h
    reportOnStart: true
    ignoreDusts: true

